name: Laravel Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-laravel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: docker compose -f docker-compose.yml up -d --build

      - name: Run Laravel setup & tests inside container
        run: |
          docker compose exec -T app cp .env.example .env
          docker compose exec -T app composer install --no-progress --prefer-dist
          docker compose exec -T app php artisan key:generate
          docker compose exec -T app php artisan migrate --force
          docker compose exec -T app php artisan test
        working-directory: ./src
