name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, pdo, pdo_mysql, zip

      - name: Install Composer dependencies
        working-directory: ./src
        run: composer install --no-progress --prefer-dist

      - name: Copy .env
        working-directory: ./src
        run: cp .env.example .env
