name: Laravel Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-laravel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and start Docker
        run: docker compose up -d --build

      - name: Allow Git in Docker container
        run: docker compose exec -T app git config --global --add safe.directory /var/www

      - name: List files in /var/www inside app container
        run: docker compose exec -T app ls -la /var/www

      - name: Install dependencies
        run: docker compose exec -T app bash -c "cd /var/www && composer install --no-progress --prefer-dist"